### PR TITLE
lxd cluster

### PR DESCRIPTION
**Pull request by sd-hd**
* added ability for lxd cluster
* added ubuntu 19.04

### CODE REVIEW

**Comment by sd-hd** [comment]
add fan network
some cleanups
fix core.https_address

**Comment by juju4** [comment]
Thanks a lot @sh-hd for contribution.

A few comments
- please keep separate functional changes, lxd cluster vs the rest
- on testing part, yes, I will probably remove trusty at some point, but no impact to leave it in tests for now.
- on testing, I won't include 19.04. only covering LTS here else there is no end to tests. fine to have a vars file for 19.04
- obviously, want to fix travis testing
https://travis-ci.org/juju4/ansible-lxd/jobs/527703816#L3142
```
    "stderr": "Error: Failed to create network 'lxdfan0': No address found in subnet", 
    "stderr_lines": [
        "Error: Failed to create network 'lxdfan0': No address found in subnet"
    ], 
```
or 
https://travis-ci.org/juju4/ansible-lxd/jobs/527703818#L3056
```
    "msg": "non-zero return code", 
    "rc": 2, 
    "start": "2019-05-03 10:14:07.766857", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "error: flag provided but not defined: --preseed", 
    "stdout_lines": [
        "error: flag provided but not defined: --preseed"
    ]
```
- is functionality available/backported in all ubuntu distributions, at least the one maintained? else need another conditional.
- need serverspec tests on cluster part to validate working
- remember to give a lint pass also once functional

**Comment by sd-hd** [comment]
Hi juju4,

currently i am refactoring.

Did you know if it is possible to create a multi machine integration test for the cluster ? 

What kind of linting did you mean ? I tried to fix all ansible warnings. The result was that on 14.04 the scripts stops working.

**Comment by juju4** [comment]
multi-machine as?
- multi lxd container inside one instance: yes, manageable by ansible
- multi-VM at kitchen level. no. multiple issues on this in the past but does not seem in the plan
https://github.com/chef-boneyard/chef-rfc/blob/master/rfc084-test-kitchen-multi.md

on linting, I mean ansible-lint as leveraged by galaxy
https://github.com/ansible/galaxy-lint-rules/blob/master/RULE_DOCS.md
no hard line on that but better.
examples:
* easy things: ensure that each task has a name
* depends: ensure command module call are idempotent either with creates args or conditional.

**Pull request closed without merging**
